### ISSUE TITLE
Update "oof" responses

### ISSUE THREAD

**Issue by mspicer60** [20BBrown14/Voice_Channel_Discord_Bot#27]
Add "Press F to pay respects", "Press F", "Can we get an F in chat?", and  "F"
Remove "you are the winner"
Italianize "nice job"
Replace "oh snap" with https://tenor.com/view/tyra-banks-finger-snap-sassy-antm-fierce-gif-4917492

**Comment by hvilander** [comment]
https://github.com/20BBrown14/Voice_Channel_Discord_Bot/pull/31
This PR address some of these, I am not sure we want to junk up things with **MORE** gifs.

**Comment by mspicer60** [comment]
I disagree but suppose you have a point
